# Generated by Django 4.0.1 on 2022-01-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('body', models.CharField(max_length=200)),
                ('to_email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=40)),
                ('sended_at', models.DateTimeField(auto_now_add=True)),
                ('looked', models.BooleanField(default=False)),
            ],
        ),
    ]
